auth-service:
  url: http://localhost:8080
spring:
  cache:
    type: caffeine
    cache-names: portfolio, constraints
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterAccess=1d
  application:
    name: portfolio-service
  profiles:
    active: ${ACTIVE_PROFILE:docker}
  aop:
    proxy-target-class: true
  data:
    mongodb:
      database: portfolio
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
server:
  error:
    include-message: always
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true